<?php
return [
    'rootPanel' => [
        'type' => 2,
        'description' => 'Root panel',
    ],
    'adminPanel' => [
        'type' => 2,
        'description' => 'Admin panel',
    ],
    'moderPanel' => [
        'type' => 2,
        'description' => 'moder Panel',
    ],
    'bossPanel' => [
        'type' => 2,
        'description' => 'boss Panel',
    ],
    'dispatcherPanel' => [
        'type' => 2,
        'description' => 'Dispatcher panel',
    ],
    'specPanel' => [
        'type' => 2,
        'description' => 'spec Panel',
    ],
    'agentPanel' => [
        'type' => 2,
        'description' => 'agent Panel',
    ],
    'governmentPanel' => [
        'type' => 2,
        'description' => 'Government panel',
    ],
    'userPanel' => [
        'type' => 2,
        'description' => 'User panel',
    ],
    'halfuserPanel' => [
        'type' => 2,
        'description' => 'halfuser Panel',
    ],
    'halfuser' => [
        'type' => 1,
        'description' => 'halfuser',
        'children' => [
            'halfuserPanel',
        ],
    ],
    'user' => [
        'type' => 1,
        'description' => 'User',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'userPanel',
        ],
    ],
    'government' => [
        'type' => 1,
        'description' => 'Government',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'user',
            'userPanel',
            'governmentPanel',
        ],
    ],
    'agent' => [
        'type' => 1,
        'description' => 'agent',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'user',
            'userPanel',
            'government',
            'governmentPanel',
            'spec',
            'specPanel',
            'agentPanel',
        ],
    ],
    'spec' => [
        'type' => 1,
        'description' => 'spec',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'user',
            'userPanel',
            'government',
            'governmentPanel',
            'specPanel',
        ],
    ],
    'dispatcher' => [
        'type' => 1,
        'description' => 'Dispatcher',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'user',
            'userPanel',
            'government',
            'governmentPanel',
            'spec',
            'specPanel',
            'agent',
            'agentPanel',
            'dispatcherPanel',
        ],
    ],
    'boss' => [
        'type' => 1,
        'description' => 'boss',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'user',
            'userPanel',
            'government',
            'governmentPanel',
            'spec',
            'specPanel',
            'agent',
            'agentPanel',
            'dispatcher',
            'dispatcherPanel',
            'bossPanel',
        ],
    ],
    'moder' => [
        'type' => 1,
        'description' => 'moder',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'user',
            'userPanel',
            'government',
            'governmentPanel',
            'spec',
            'specPanel',
            'agent',
            'agentPanel',
            'dispatcher',
            'dispatcherPanel',
            'boss',
            'bossPanel',
            'moderPanel',
        ],
    ],
    'admin' => [
        'type' => 1,
        'description' => 'Admin',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'user',
            'userPanel',
            'government',
            'governmentPanel',
            'spec',
            'specPanel',
            'agent',
            'agentPanel',
            'dispatcher',
            'dispatcherPanel',
            'boss',
            'bossPanel',
            'moder',
            'moderPanel',
            'adminPanel',
        ],
    ],
    'root' => [
        'type' => 1,
        'description' => 'root',
        'children' => [
            'halfuser',
            'halfuserPanel',
            'user',
            'userPanel',
            'government',
            'governmentPanel',
            'spec',
            'specPanel',
            'agent',
            'agentPanel',
            'dispatcher',
            'dispatcherPanel',
            'boss',
            'bossPanel',
            'moder',
            'moderPanel',
            'admin',
            'adminPanel',
            'rootPanel',
        ],
    ],
];
